application: gaudencode
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap/
  static_dir: assets/bootstrap

- url: /pubreader/
  static_dir: assets/pubreader

- url: /css/
  static_dir: assets/css

- url: /font/
  static_dir: assets/font

- url: /img/
  static_dir: assets/img

- url: /js/
  static_dir: assets/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"                                                                      
- name: jinja2                                                                  
  version: latest